/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example


// Escribir una interface perimetrable con un metodo calcularPerimetro()
interface perimetrable {
    fun calcularPerimetro(): Double
}


class Coche(private var _marca: String = "Ford", private var _modelo: Int = 2020) {
    var marca: String
        get() = _marca
        set(value) {
            _marca = value
        }
    var modelo: Int
        get() = _modelo
        set(value) {
            _modelo = value
        }
}

// Escribir una clase Rectangulo que implemente la interface Perimetrable


class Rectangulo(val ancho: Double, val alto: Double) {
    var area: Double

    // El bloque init se usa para inicializar propiedades o ejecutar código en la creación.
    init {
        // 'area' se calcula una vez cuando se crea el objeto.
        area = ancho * alto
        println("Se ha creado un rectángulo de $ancho x $alto con un área de $area")
    }

    // Un método de la clase
    fun describir() {
        println("Este es un rectángulo.")
    }

    // Implementación del método de la interfaz perimetrable
    fun calcularPerimetro(): Double {
        return 2 * (ancho + alto)
    }
}

// Escribir una clase Circulo que implemente la interface Perimetrable

class Circulo(val radio: Double) : perimetrable {
    override fun calcularPerimetro(): Double {
        return 2 * Math.PI * radio
    }
}



fun main() {

    val coche = Coche("Chevrolet", 2025)

    println("Marca ${coche.marca}")
    println("Modelo ${coche.modelo}")
    var rectangulo = Rectangulo(10.0, 5.0)
     println("Área del rectángulo: ${rectangulo.area}")
    var circulo = Circulo(7.0)
    println("Perímetro del círculo: ${circulo.calcularPerimetro()}")

}




